/* Generated By:JJTree: Do not edit this line. ASTHello.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package codezine.hello.parser;

public
class ASTHello extends SimpleNode {
  public ASTHello(int id) {
    super(id);
  }

  public ASTHello(HelloParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HelloParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1264981e9015b1a9ac7cc11d2378c75b (do not edit this line) */
