/* Generated By:JJTree: Do not edit this line. ASTJJTree.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package codezine.hello.parser;

public
class ASTJJTree extends SimpleNode {
  public ASTJJTree(int id) {
    super(id);
  }

  public ASTJJTree(HelloParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HelloParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dfd13bd4acf7c1f398a1489af47fce47 (do not edit this line) */
