/* Generated By:JJTree: Do not edit this line. ASTJavaCC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package codezine.hello.parser;

public
class ASTJavaCC extends SimpleNode {
  public ASTJavaCC(int id) {
    super(id);
  }

  public ASTJavaCC(HelloParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HelloParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d06c0fcf046dca5712da798ab956eebf (do not edit this line) */
