/* Generated By:JavaCC: Do not edit this line. HelloParserVisitor.java Version 5.0 */
package codezine.hello.parser;

public interface HelloParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTHello node, Object data);
  public Object visit(ASTJavaCC node, Object data);
  public Object visit(ASTJJTree node, Object data);
  public Object visit(ASTName node, Object data);
}
/* JavaCC - OriginalChecksum=2e47e2eaeefd19f45cce014d9c1533af (do not edit this line) */
