/* Generated By:JavaCC: Do not edit this line. HelloParserTreeConstants.java Version 5.0 */
package codezine.hello.parser;

public interface HelloParserTreeConstants
{
  public int JJTHELLO = 0;
  public int JJTVOID = 1;
  public int JJTJAVACC = 2;
  public int JJTJJTREE = 3;


  public String[] jjtNodeName = {
    "Hello",
    "void",
    "JavaCC",
    "JJTree",
  };
}
/* JavaCC - OriginalChecksum=2d325d3bbe4a95d9354b5a48f434e3f9 (do not edit this line) */
