/* Generated By:JavaCC: Do not edit this line. HelloParserTreeConstants.java Version 5.0 */
package codezine.hello.parser;

public interface HelloParserTreeConstants
{
  public int JJTHELLO = 0;
  public int JJTVOID = 1;
  public int JJTJAVACC = 2;
  public int JJTJJTREE = 3;
  public int JJTNAME = 4;


  public String[] jjtNodeName = {
    "Hello",
    "void",
    "JavaCC",
    "JJTree",
    "Name",
  };
}
/* JavaCC - OriginalChecksum=86ad4a3f6e884d02b7cee18c4ded5662 (do not edit this line) */
