/* Generated By:JJTree&JavaCC: Do not edit this line. HelloParserConstants.java */
package codezine.hello.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HelloParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HELLO = 5;
  /** RegularExpression Id. */
  int JAVACC = 6;
  /** RegularExpression Id. */
  int JJTREE = 7;
  /** RegularExpression Id. */
  int NAME = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"hello\"",
    "\"javacc\"",
    "\"jjtree\"",
    "<NAME>",
  };

}
