/* Generated By:JavaCC: Do not edit this line. HelloParserVisitor.java Version 5.0 */
package codezine.hello.parser;

public interface HelloParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTHello node, Object data);
  public Object visit(ASTJavaCC node, Object data);
  public Object visit(ASTJJTree node, Object data);
}
/* JavaCC - OriginalChecksum=f30ed291263fa1e7dc3816c7078d6b32 (do not edit this line) */
