/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 5.0 */
package codezine.expr.parser;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=572c4514b7b58a4ea278f6d9c44f5e8b (do not edit this line) */
