/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 5.0 */
package codezine.expr.parser;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMulti node, Object data);
  public Object visit(ASTDivision node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=56b24c0c5ac0a2d3f9d3e4230f37d67b (do not edit this line) */
