/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 5.0 */
package codezine.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTINTEGER = 4;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=d511ed9514dacba3cbe6502e56b9f511 (do not edit this line) */
