/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 5.0 */
package codezine.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMULTI = 4;
  public int JJTDIVISION = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Multi",
    "Division",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=6810a1e069d8bb7feb1da3395147fa29 (do not edit this line) */
